// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinKeg.DB;

namespace WinKeg.DB.Migrations
{
    [DbContext(typeof(WinKegContext))]
    partial class WinKegContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("WinKeg.DB.Models.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ABV")
                        .HasColumnType("REAL");

                    b.Property<int?>("BeverageImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("IBU")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeverageImageId");

                    b.ToTable("Beverages");
                });

            modelBuilder.Entity("WinKeg.DB.Models.BeverageImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageBlob")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BeverageImages");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KegId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KegeratorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KegId");

                    b.HasIndex("KegeratorId");

                    b.ToTable("Hardware");
                });

            modelBuilder.Entity("WinKeg.DB.Models.HistoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KegHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KegHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("HistoryEvents");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Keg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentVolume")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialVolume")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kegs");
                });

            modelBuilder.Entity("WinKeg.DB.Models.KegHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BeverageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KegId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeverageId");

                    b.HasIndex("KegId");

                    b.ToTable("KegHistories");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Kegerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kegerator");
                });

            modelBuilder.Entity("WinKeg.DB.Models.KegeratorEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KegeratorEvents");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("WinKeg.DB.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncryptedPasscode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBeverageRestricted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PCSalt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Beverage", b =>
                {
                    b.HasOne("WinKeg.DB.Models.BeverageImage", "BeverageImage")
                        .WithMany("Beverages")
                        .HasForeignKey("BeverageImageId");
                });

            modelBuilder.Entity("WinKeg.DB.Models.Hardware", b =>
                {
                    b.HasOne("WinKeg.DB.Models.Keg", "Keg")
                        .WithMany("KegHardware")
                        .HasForeignKey("KegId");

                    b.HasOne("WinKeg.DB.Models.Kegerator", "Kegerator")
                        .WithMany("KegeratorHardware")
                        .HasForeignKey("KegeratorId");
                });

            modelBuilder.Entity("WinKeg.DB.Models.HistoryEvent", b =>
                {
                    b.HasOne("WinKeg.DB.Models.KegHistory", null)
                        .WithMany("HistoryEvents")
                        .HasForeignKey("KegHistoryId");

                    b.HasOne("WinKeg.DB.Models.User", "User")
                        .WithMany("HistoryEvents")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("WinKeg.DB.Models.KegHistory", b =>
                {
                    b.HasOne("WinKeg.DB.Models.Beverage", "Beverage")
                        .WithMany("KegHistories")
                        .HasForeignKey("BeverageId");

                    b.HasOne("WinKeg.DB.Models.Keg", "Keg")
                        .WithMany("KegHistories")
                        .HasForeignKey("KegId");
                });
#pragma warning restore 612, 618
        }
    }
}
